version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: CONTAINER_NAME
          ContainerPort: CONTAINER_PORT
        CapacityProviderStrategy:
          - Base: 0
            CapacityProvider: FARGATE
            Weight: 2
