Parameters:
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: hmoon

  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: wsi

  CacheName:
    Type: String
    Description: "The prefix of resource's Name tag"
    Default: wsi-redis-cluster

  CacheParameterGroupFamily:
    Type: String
    Default: redis7

  EngineVersion:
    Type: String
    Description: Version of redis cluster. aws elasticache describe-cache-engine-versions --engine redis --cache-parameter-group-family redis7
    Default: "7.0"

  CacheNodeType:
    Type: String
    Description: Cache node type 
    Default: cache.m6g.large

  ShardCount:
    Type: Number
    Default: 2

  ReplicaCountPerShard:
    Type: Number
    Description: Consider subnet counts to be equal to 1(primary) + replicas
    Default: 1

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Tag configuration"
        Parameters:
          - Project
          - Owner
      - Label:
          default: "Cache Configuration"
        Parameters:
          - CacheName
          - CacheParameterGroupFamily
          - EngineVersion
          - CacheNodeType
          - ShardCount
          - ReplicaCountPerShard
      - Label:
          default: "Cache Network Configuration"
        Parameters:
          - SubnetIds
          - SecurityGroupIds

Resources:
  #
  # Cloudwatch Logs - Log Group
  #
  ElasticacheLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/elasticache/${CacheName}"
      RetentionInDays: 7 # days

  #
  # Elasticache - Parameter Group
  #
  ElasticacheParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      # memcached1.4 | memcached1.5 | memcached1.6
      # redis2.6 | redis2.8 | redis3.2 | redis4.0 | redis5.0 | redis6.x
      CacheParameterGroupFamily: !Ref CacheParameterGroupFamily
      Description: "This is redis cluster parameter group"
      Properties:
        cluster-enabled: "yes"

  #
  # Elasticache - Subnet Group
  #
  ElasticacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: !Sub "${CacheName}-subnetgroup"
      Description: "This is redis cluster subnet group"
      SubnetIds: !Ref SubnetIds

  #
  # Elasticache - Replication Group
  #
  ElasticacheReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    DeletionPolicy: Delete
    Properties:
      ReplicationGroupId: !Sub "${CacheName}"
      ReplicationGroupDescription: "This is Elasticache Redis (cluster mode enabled)"
      Engine: redis # memcached | redis
      EngineVersion: !Ref EngineVersion # aws elasticache describe-cache-engine-versions
      CacheNodeType: !Ref CacheNodeType
      NumNodeGroups: !Ref ShardCount
      ReplicasPerNodeGroup: !Ref ReplicaCountPerShard
      Port: 6379
      CacheParameterGroupName: !Ref ElasticacheParameterGroup
      CacheSubnetGroupName: !Ref ElasticacheSubnetGroup
      SecurityGroupIds: !Ref SecurityGroupIds
      MultiAZEnabled: true
      AutomaticFailoverEnabled: true
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      # KmsKeyId: String
      # AuthToken: String
      AutoMinorVersionUpgrade: true
      # SnapshotWindow: String
      SnapshotRetentionLimit: 1
      # DataTieringEnabled: Boolean
      LogDeliveryConfigurations:
        - DestinationDetails:
            CloudWatchLogsDetails:
              LogGroup: !Ref ElasticacheLogGroup
          DestinationType: cloudwatch-logs # cloudwatch-logs | kinesis-firehose
          LogFormat: json # json | text
          LogType: slow-log # slow-log | engine-log
        - DestinationDetails:
            CloudWatchLogsDetails:
              LogGroup: !Ref ElasticacheLogGroup
          DestinationType: cloudwatch-logs # cloudwatch-logs | kinesis-firehose
          LogFormat: json # json | text
          LogType: engine-log # slow-log | engine-log
      # SnapshotArns:
      #   - String
      # UserGroupIds:
      #   - String
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner
