Parameters:
  AutoScalingGroupName:
    Type: String
    Description: "The Name of Auto Scaling Group"
    Default: wsi-app

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "The Subnet Ids for launched instances"

  TargetGroupARNs:
    Type: CommaDelimitedList
    Description: "The Target Group Arns that will be attached instance to alb"

  AMI:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Description: "The AMI for launched instances"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"

  InstanceType:
    Type: String
    Description: "Instance type for instances"
    Default: t3.medium

  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "The Keypair for launched instances"

  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: "The Security Group Ids for launched instances"

  Project:
    Type: String
    Description: "The project name for provisioned this resources"
    Default: wsi

  Owner:
    Type: String
    Description: "The team name for owned this resources"
    Default: hmoon

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "ASG configuration"
        Parameters:
          - AutoScalingGroupName
          - SubnetIds
          - TargetGroupARNs
      - Label:
          default: "Instance Configuration"
        Parameters:
          - AMI
          - InstanceType
          - KeyPair
          - SecurityGroupIds
      - Label:
          default: "Tag Configuration"
        Parameters:
          - Project
          - Owner

Resources:
  #
  # IAM Role
  #
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AutoScalingGroupName}-role"
      Description: !Sub "The role for ${AutoScalingGroupName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Owner
          Value: !Ref Owner

  #
  # IAM Instance Profile
  #
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub "${AutoScalingGroupName}-role"
      Path: /
      Roles:
        - !Ref Role

  #
  # LaunchTemplate
  #
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub "${AutoScalingGroupName}-lt"
      LaunchTemplateData:
        ImageId: !Ref AMI
        InstanceType: !Ref InstanceType
        SecurityGroupIds: !Ref SecurityGroupIds
        IamInstanceProfile:
          Name: !Ref InstanceProfile

        UserData:
          Fn::Base64: ""

        KeyName: !Ref KeyPair
        Monitoring:
          Enabled: true
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              DeleteOnTermination: true
              VolumeType: gp3
              VolumeSize: 10
              Iops: 3000
              Throughput: 125
              Encrypted: true
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub "${AutoScalingGroupName}-worker"
              - Key: Project
                Value: !Ref Project
              - Key: Owner
                Value: !Ref Owner
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub "${AutoScalingGroupName}-worker"
              - Key: Project
                Value: !Ref Project
              - Key: Owner
                Value: !Ref Owner
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: Name
              Value: !Sub "${AutoScalingGroupName}-lt"

  #
  # Auto Scaling Group
  #
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroupName
      Cooldown: "120"
      DesiredCapacityType: units
      MinSize: "2"
      MaxSize: "20"
      HealthCheckGracePeriod: 60
      HealthCheckType: ELB
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - PropagateAtLaunch: true
          Key: Name
          Value: !Sub "${AutoScalingGroupName}-worker"
      TargetGroupARNs: !Ref TargetGroupARNs
      VPCZoneIdentifier: !Ref SubnetIds

  #
  # Scaling Policy
  #
  TargetTrackingScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      PolicyType: TargetTrackingScaling # TargetTrackingScaling | StepScaling | SimpleScaling
      AutoScalingGroupName: !Ref AutoScalingGroup
      TargetTrackingConfiguration:
        DisableScaleIn: False
        PredefinedMetricSpecification:
          # Available Value : ASGAverageCPUUtilization | ASGAverageNetworkIn | ASGAverageNetworkOut | ALBRequestCountPerTarget
          PredefinedMetricType: ASGAverageCPUUtilization
          # ResourceLabel: String # When Using ALBRequestCountPerTarget
        TargetValue: 60
